services:
  guacamole:
    container_name: Guacamole
    image: jwetzell/guacamole
    healthcheck:
     test: curl -f http://localhost:8080/ || exit 1
    mem_limit: 6g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:false
    restart: always # Or unless-stopped
    ports:
      - '8348:8080'
    volumes:
      - ${APP_DATA_DIR}/data/guacamole:/config:rw
    environment:
      PUID: 1027
      PGID: 101
      TZ: America/Toronto
